---
- name: configure a webserver
  hosts: clientnode
  become: true
  become_user: root
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: start the httpd
      ansible.builtin.service:
        name: httpd
        state: started
    - name: Copy from ansible to remote
      ansible.builtin.copy:
        src: /home/ec2-user/ansi_labs/index.html
        dest: /home/ec2-user/index.html
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
